# Week 4 · Day 1 — Learn: Meet NumPy & Arrays
### Code to AI — Python & Data Science (from Zero to Portfolio)
**Instructor:** Ali Hasnain

---
**Goal for today:** understand *why* NumPy exists, create arrays, index/slice them, and do math on whole arrays at once (no loops!).

**Session plan (~75 min):**
| Time | Segment |
|------|---------|
| 0–8 min | Why NumPy? Lists vs arrays |
| 8–20 min | Creating arrays & array attributes |
| 20–35 min | Array creation shortcuts (arange, linspace, zeros...) |
| 35–50 min | Indexing & slicing (1D + 2D) |
| 50–68 min | Vectorized math + broadcasting (the big reveal) |
| 68–75 min | Mini demo + wrap-up + assignment |


## 1. Why NumPy? (0–8 min)

So far we have used Python **lists** to store many values. Lists are great, but when we want to do **math on lots of numbers**, they become slow and clumsy.

NumPy gives us a new tool: the **array**. An array looks like a list, but it is built for math. With arrays we can add, multiply, or average thousands of numbers in one short line — and it runs very fast.

This is the foundation for everything ahead: NumPy powers Pandas (Week 5–6), plotting (Week 7), and machine learning (Week 8).

In [1]:
# The problem with lists: math is not automatic.
temps_list = [30, 32, 28, 35]

# If we want to add 5 to every temperature, a list makes us loop:
result = []
for t in temps_list:
    result.append(t + 5)
print(result)

[35, 37, 33, 40]


In [3]:
!pip install numpy -q

In [4]:
import numpy as np 

In [5]:
np.array([1,2,3,5])

array([1, 2, 3, 5])

In [7]:
# With NumPy, the same thing is ONE line. Let's meet NumPy.
import numpy as np   # 'np' is the standard nickname everyone uses

temps = np.array([30, 32, 28, 35])
print(temps)
print(temps + 5)     # adds 5 to EVERY element automatically
print(temps - 2)
print(temps * 2)

[30 32 28 35]
[35 37 33 40]
[28 30 26 33]
[60 64 56 70]


## 2. Creating arrays & attributes (8–20 min)

We make an array with `np.array(...)` and pass a list inside.

Every array has useful **attributes** that describe it:
- `shape` → the size in each dimension
- `ndim` → number of dimensions (1D, 2D, ...)
- `size` → total number of elements
- `dtype` → the data type of the elements

In [8]:
a = np.array([10, 20, 30, 40, 50])
print("array:", a)
print("shape:", a.shape)   # (5,) means 5 elements in one row
print("ndim :", a.ndim)    # 1  -> one dimension
print("size :", a.size)    # 5  -> total elements
print("dtype:", a.dtype)   # int64 -> whole numbers

array: [10 20 30 40 50]
shape: (5,)
ndim : 1
size : 5
dtype: int64


In [9]:
# A 2D array is like a table (rows and columns) — a list of lists.
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(grid)
print("shape:", grid.shape)  # (2, 3) -> 2 rows, 3 columns
print("ndim :", grid.ndim)   # 2

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
ndim : 2


## 3. Array creation shortcuts (20–35 min)

We do not always type numbers by hand. NumPy can generate arrays for us:
- `np.arange(start, stop, step)` → like `range()`, but returns an array
- `np.linspace(start, stop, n)` → n evenly spaced numbers (endpoints included)
- `np.zeros(n)` / `np.ones(n)` → arrays filled with 0 or 1
- `np.full(n, value)` → filled with any value
- `np.random.randint(low, high, size)` → random whole numbers

In [11]:
print(np.arange(0, 100, 2))       # [0 2 4 6 8]

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
print(np.linspace(0,10,100))

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [18]:
print(np.linspace(0,1,100))

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [24]:
print(np.zeros(100))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [26]:
print(np.ones(50))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [28]:
print(np.full(25,100))

[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100]


In [ ]:
print(np.arange(0, 10, 2))       # [0 2 4 6 8]
print(np.linspace(0, 1, 5))      # 5 numbers from 0 to 1
print(np.zeros(4))               # [0. 0. 0. 0.]
print(np.ones(3))                # [1. 1. 1.]
print(np.full(3, 7))             # [7 7 7]

In [31]:
# [29 37 14 38 89 37]

In [35]:
# [52 93 15 72 61 21]

In [37]:
# Random numbers are great for testing ideas.
np.random.seed(42)   # seed makes results repeatable (same 'random' each run)
print(np.random.randint(1, 100, size=6))

[52 93 15 72 61 21]


## 4. Indexing & slicing (35–50 min)

Indexing works like lists: positions start at **0**, and negative numbers count from the end.

Slicing uses `start:stop` (stop is **not** included).

For 2D arrays we use `array[row, column]`.

In [38]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])      # 10  -> first element
print(a[-1])     # 50  -> last element
print(a[1:4])    # [20 30 40] -> positions 1,2,3
print(a[:3])     # [10 20 30] -> first three

10
50
[20 30 40]
[10 20 30]


In [39]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(grid[0, 0])   # 1  -> row 0, col 0
print(grid[1, 2])   # 6  -> row 1, col 2
print(grid[0])      # [1 2 3] -> whole first row
print(grid[:, 0])   # [1 4 7] -> whole first column

1
6
[1 2 3]
[1 4 7]


In [42]:
print(grid[:,2])

[3 6 9]


## 5. Vectorized math + broadcasting (50–68 min) — THE BIG REVEAL

This is the superpower of NumPy.

**Vectorized math:** an operation applies to *every element at once* — no loop needed.

**Broadcasting:** a single number (a scalar) automatically stretches to match the whole array.

In [43]:
prices = np.array([100, 200, 300, 400])

print(prices + 10)    # add 10 to each
print(prices * 2)     # double each
print(prices / 100)   # divide each
print(prices - 50)    # subtract from each

[110 210 310 410]
[200 400 600 800]
[1. 2. 3. 4.]
[ 50 150 250 350]


In [44]:
# Two arrays of the same shape combine element-by-element.
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)   # [11 22 33]
print(a * b)   # [10 40 90]

[11 22 33]
[10 40 90]


## 6. Mini demo + wrap-up (68–75 min)

**Live demo:** convert Celsius temperatures to Fahrenheit in ONE line.
Formula: `F = C * 9/5 + 32`

In [45]:
celsius = np.array([0, 20, 30, 37, 100])
fahrenheit = celsius * 9/5 + 32
print("Celsius   :", celsius)
print("Fahrenheit:", fahrenheit)

Celsius   : [  0  20  30  37 100]
Fahrenheit: [ 32.   68.   86.   98.6 212. ]


### Recap — what we learned today
- **Why NumPy:** fast math on many numbers, no loops
- **Arrays:** `np.array`, and attributes `shape`, `ndim`, `size`, `dtype`
- **Creating:** `arange`, `linspace`, `zeros`, `ones`, `full`, `random`
- **Indexing/slicing:** 1D and 2D (`array[row, col]`)
- **Vectorized math + broadcasting:** the "no loops needed" superpower

**Next class (Day 2):** statistics on arrays — mean, median, std, filtering with conditions.

📌 **Assignment:** open `day1_assignment.ipynb` and complete it before the next class. Post your GitHub repo link in the WhatsApp group. 🚀