# Week 4 · Day 2 — Practice: Statistics & Aggregations
### Code to AI — Python & Data Science (from Zero to Portfolio)
**Instructor:** Ali Hasnain

---
**Goal for today:** turn arrays into **insights** — averages, spread, filtering with conditions, and reshaping.

**Session plan (~75 min):**
| Time | Segment |
|------|---------|
| 0–12 min | Aggregations: sum, mean, median, min, max |
| 12–25 min | Spread: std & var (visual intuition) |
| 25–40 min | The `axis` idea (rows vs columns) |
| 40–55 min | Boolean masks & filtering |
| 55–66 min | `np.where` for labeling |
| 66–75 min | Reshaping + wrap-up |


## 1. Aggregations (0–12 min)

An **aggregation** takes many numbers and returns one summary number.
NumPy gives us these directly:
- `.sum()` — total
- `.mean()` — average
- `np.median()` — middle value
- `.min()` / `.max()` — smallest / largest

In [1]:
import numpy as np

scores = np.array([70, 85, 90, 60, 75, 95, 80])

In [2]:
print(scores)

[70 85 90 60 75 95 80]


In [3]:
print("sum   :", scores.sum())

sum   : 555


In [4]:
print("mean  :", scores.mean())

mean  : 79.28571428571429


In [5]:
print("median:", np.median(scores))

median: 80.0


In [6]:
print("min   :", scores.min())

min   : 60


In [7]:
print("max   :", scores.max())

max   : 95


## 2. Spread: std & var (12–25 min)

The **mean** tells us the center. But two groups can have the same mean and still look very different — one tightly packed, one spread out.

- **Standard deviation** (`.std()`) measures how spread out the numbers are.
- **Variance** (`.var()`) is the standard deviation squared.

Small std = numbers are close together. Large std = numbers are spread out.

In [8]:
tight = np.array([49, 50, 51, 50, 50])   # all near 50
spread = np.array([10, 90, 30, 70, 50])  # far apart

print("tight  mean:", tight.mean(),  "std:", round(tight.std(), 2))
print("spread mean:", spread.mean(), "std:", round(spread.std(), 2))
# Same-ish mean, very different spread!

tight  mean: 50.0 std: 0.63
spread mean: 50.0 std: 28.28


In [9]:
import numpy as np

a = np.array([48, 49, 50, 51, 52])

print("Mean:", np.mean(a))
print("Standard Deviation:", np.std(a))

Mean: 50.0
Standard Deviation: 1.4142135623730951


In [10]:
import numpy as np

b = np.array([10, 30, 50, 70, 90])

print("Mean:", np.mean(b))
print("Standard Deviation:", np.std(b))

Mean: 50.0
Standard Deviation: 28.284271247461902


## 3. The `axis` idea (25–40 min) — taught visually

For a 2D array (a table), we can aggregate in three ways:

```
             col0  col1  col2
   row0  ->   [ 1,   2,   3 ]
   row1  ->   [ 4,   5,   6 ]
```

- `axis=0` → go **down** the columns (one result per column)
- `axis=1` → go **across** the rows (one result per row)
- no axis → one number for the whole array

Tip: `axis=0` collapses rows, `axis=1` collapses columns.

In [11]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("whole sum :", grid.sum())          # 21

whole sum : 21


In [12]:
print("col sums  :", grid.sum(axis=0))    # [5 7 9]  (down columns)

col sums  : [5 7 9]


In [13]:


print("row sums  :", grid.sum(axis=1))    # [6 15]   (across rows)

row sums  : [ 6 15]


In [14]:
# Same idea with mean — useful for real tables
print("column averages:", grid.mean(axis=0))
print("row averages   :", grid.mean(axis=1))

column averages: [2.5 3.5 4.5]
row averages   : [2. 5.]


## 4. Boolean masks & filtering (40–55 min)

Remember comparison operators from Week 3? On arrays, a comparison returns an array of **True/False** — a **mask**.

We can then use that mask to **pull out** only the elements we want. This is one of the most useful tools in data analysis.

In [15]:
temps = np.array([31, 28, 35, 33, 26, 37, 30])

mask = temps > 32          # a True/False array
print("mask      :", mask)


mask      : [False False  True  True False  True False]


In [16]:
print("hot days  :", temps[mask])       # only values where mask is True


hot days  : [35 33 37]


In [17]:
# We can count and combine conditions too
print("how many hot days:", (temps > 32).sum())   # True counts as 1


how many hot days: 3


In [18]:
print("mild days        :", temps[temps < 30])

mild days        : [28 26]


## 5. `np.where` for labeling (55–66 min)

`np.where(condition, value_if_true, value_if_false)` builds a new array by choosing a value for each element based on a condition. Great for **labeling** data.

In [19]:
temps = np.array([31, 28, 35, 33, 26, 37, 30])

labels = np.where(temps > 32, "HOT", "OK")
print(labels)



['OK' 'OK' 'HOT' 'HOT' 'OK' 'HOT' 'OK']


In [20]:
# It also works with numbers (e.g., cap values)
capped = np.where(temps > 34, 34, temps)   # anything above 34 becomes 34
print(capped)

[31 28 34 33 26 34 30]


## 6. Reshaping (66–75 min)

Sometimes we need to change an array's shape without changing its data.
- `reshape(rows, cols)` → rearrange into a new shape (total size must match)
- `flatten()` → squash a 2D array back into 1D

In [22]:
a = np.arange(1, 13)     # 12 numbers: 1..12
print("original:", a)

grid = a.reshape(3, 4)   # 3 rows, 4 cols  (3*4 = 12)
print(grid)

grid_2 = a.reshape(4,3)
print(grid_2)

original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Recap — what we learned today
- **Aggregations:** sum, mean, median, min, max
- **Spread:** std & var (small = tight, large = spread out)
- **axis:** `axis=0` down columns, `axis=1` across rows
- **Boolean masks:** filter with conditions → `arr[arr > x]`
- **`np.where`:** label or transform based on a condition
- **Reshaping:** `reshape` and `flatten`

**Next class (Day 3):** load a REAL CSV and build a data-analysis project for GitHub. 🚀

📌 **Assignment:** open `day2_assignment.ipynb` and complete it before the next class.